# ==========================================
# config-repo/application-dev.yml (모든 서비스 개발환경 공통)
# ==========================================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  # 개발환경 공통 데이터베이스 설정
  datasource:
    url: ${DEV_DB_URL:jdbc:mariadb://localhost:3306/shopmalls?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul}
    username: ${DEV_DB_USERNAME:kosa}
    password: ${DEV_DB_PASSWORD:1004}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Redis 개발환경
  redis:
    host: ${DEV_REDIS_HOST:localhost}
    port: ${DEV_REDIS_PORT:6379}
    password: ${DEV_REDIS_PASSWORD:}

  # RabbitMQ 개발환경
  rabbitmq:
    host: ${DEV_RABBITMQ_HOST:localhost}
    port: ${DEV_RABBITMQ_PORT:5672}
    username: ${DEV_RABBITMQ_USERNAME:guest}
    password: ${DEV_RABBITMQ_PASSWORD:guest}

  # Kafka 개발환경
  kafka:
    bootstrap-servers: ${DEV_KAFKA_SERVERS:localhost:9092}

jwt:
  secret-key: ${DEV_JWT_SECRET_KEY:verySecretKeyThatIsAtLeast32BytesLong1234}

management:
  endpoints:
    web:
      exposure:
        include: ["refresh", "busrefresh", "prometheus", "health", "info"]
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
    metrics:
      export:
        prometheus:
          enabled: true
      tags:
        application: ${spring.application.name}
  security:
    enabled: false

logging:
  level:
    org.kosa: DEBUG
    org.springframework.security: DEBUG
