server:
  port: 8090

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/shoppingmall_db
    username: shopmall_user
    password: shopmall_pass123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  redis:
    host: redis
    port: 6379
    timeout: 5000ms

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: commerce-service-group-prod

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

# 결제 설정
payment:
  test:
    enabled: false
    mode: production
  providers:
    iamport:
      api-key: ${PROD_IAMPORT_API_KEY}
      api-secret: ${PROD_IAMPORT_API_SECRET}
      enabled: true
    kakaopay:
      enabled: true
      test-mode: false

# 이미지 설정
image:
  upload:
    path: ${PROD_IMAGE_UPLOAD_PATH:/app/uploads/products/}
    max-file-size: 50MB
  base-url: ${PROD_IMAGE_BASE_URL}

logging:
  level:
    org.kosa.commerceservice: INFO
