spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_GIT_URI}
          username: ${CONFIG_GIT_USERNAME:}
          password: ${CONFIG_GIT_PASSWORD:}
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 10
          search-paths: "/"

security:
  user:
    name: ${CONFIG_SERVER_USERNAME:config}
    password: ${CONFIG_SERVER_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "prometheus"]
  security:
    enabled: true

logging:
  level:
    org.springframework.cloud.config: INFO
