server:
  port: 8090

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shopmalls?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: kosa
    password: 1004
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: commerce-service-group-dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# 결제 설정
payment:
  test:
    enabled: true
    mode: development
  providers:
    kakaopay:
      enabled: true
      test-mode: true

# 이미지 설정
image:
  upload:
    path: ./dev-uploads/images/
    max-file-size: 10MB
  base-url: http://localhost:8090/api/images/products/

logging:
  level:
    org.kosa.commerceservice: DEBUG
