server:
  port: 8888 # Config Service 포트

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/live_commerce_db
    username: kosa
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  redis:
    host: redis
    port: 6379
    timeout: 5000ms

  kafka:
    bootstrap-servers: kafka:9092

# Eureka 클라이언트 설정 추가
eureka:
  client:
    service-url:
      defaultZone: ${PROD_EUREKA_SERVER_URL:http://eureka-service:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# 결제 설정
payment:
  test:
    enabled: false
    mode: production
  providers:
    iamport:
      api-key: ${PROD_IAMPORT_API_KEY}
      api-secret: ${PROD_IAMPORT_API_SECRET}
      enabled: true
    kakaopay:
      enabled: true
      test-mode: false

# 이미지 설정
image:
  upload:
    path: ${PROD_IMAGE_UPLOAD_PATH:/app/uploads/products/}
    max-file-size: 50MB
  base-url: ${PROD_IMAGE_BASE_URL}

logging:
  level:
    org.kosa.commerceservice: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
