spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/fhohf/config-repo
        # Git 설정을 빈 값으로 추가 (에러 방지)
        # git:
        #   uri: ""
        #   clone-on-start: false

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
  security:
    enabled: false

logging:
  level:
    org.springframework.cloud.config: DEBUG
