spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: live-streaming-group
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.kosa.livestreamingservice.dto.alarm"
        spring.json.value.default.type: org.kosa.livestreamingservice.dto.alarm.NotificationMessageDto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 3
      batch-size: 16384
      linger-ms: 10
      buffer-memory: 33554432

notification:
  email:
    enabled: true
    from-email: ${DEV_NOTIFICATION_FROM_EMAIL:noreply@localhost.com}
    from-name: ${DEV_NOTIFICATION_FROM_NAME:Local Dev Notification}
    retry-count: 1
    retry-delay: 2000
  websocket:
    enabled: true
  batch:
    enabled: true
    reminder-job-cron: "0 */1 * * * *"

external-services:
  user-service-detail-url: ${DEV_USER_SERVICE_DETAIL_URL:http://localhost:8081/api/users}
  broadcast-service-url: ${DEV_BROADCAST_SERVICE_URL:http://localhost:8082/api/broadcasts}
  frontend-base-url: ${DEV_FRONTEND_BASE_URL:http://localhost:3000}
  unsubscribe-url: ${DEV_UNSUBSCRIBE_URL:http://localhost:3000/unsubscribe}

logging:
  level:
    org.kosa.notificationservice: DEBUG
    org.springframework.mail: DEBUG
    org.springframework.kafka: WARN

user-service:
  url: http://localhost:8103

streaming:
  nginx:
    host: localhost # 실제 Docker 서버 IP로 변경 (예: 192.168.1.100)
    hls-port: 8080 # Nginx HLS 포트
    rtmp-port: 1935

# MyBatis 설정 추가
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.kosa.livestreamingservice.domain
  configuration:
    map-underscore-to-camel-case: true
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        minimumNumberOfCalls: 5

  retry:
    instances:
      user-service:
        maxAttempts: 3
        waitDuration: 1s

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
