spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # Cache 설정
  cache:
    type: redis
    redis:
      cache-null-values: false

# 서버 설정
server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 커스텀 설정
app:
  icon:
    base-url: /icons

# 모니터링 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,cache
  endpoint:
    health:
      show-details: when_authorized

# Actuator 정보 설정
info:
  app:
    name: ${spring.application.name}
    description: 통합된 상품 카탈로그 서비스 (Product + Category + Image)
    version: 1.0.0

# 외부 서비스 URL
user-service-detail-url: http://user-service/api/users
