spring:
  datasource:
    # url: jdbc:mariadb://192.168.4.48:3306/shopmall
    # username: root
    # password: 1004
    # driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shopmalls?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: kosa
    password: 1004
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  # Redis 설정 (개발환경)
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

# 커스텀 설정
app:
  icon:
    base-url: /icons

# 이미지 설정 (개발환경 - Windows 경로)
image:
  upload:
    path: ${IMAGE_UPLOAD_PATH:./dev-uploads/images/}
    max-file-size: 10MB
    max-request-size: 10MB
  base-url: http://localhost:8090/api/images/products/

# 캐시 설정 (개발환경)
cache:
  product:
    detail:
      ttl: 3600
    list:
      ttl: 600
    category:
      ttl: 1800
    related:
      ttl: 1200
  category:
    main:
      ttl: 7200
    children:
      ttl: 1800

# 외부 서비스 URL
user-service-detail-url: http://user-service/api/users

# JWT 설정
jwt:
  secret: "verySecretKeyThatIsAtLeast32BytesLong1234"

# 로깅 설정 (개발환경)
logging:
  level:
    com.yourcompany.productcatalog: DEBUG
    org.kosa.categoryservice: DEBUG
    org.kosa.productservice: DEBUG
    org.kosa.imageservice: DEBUG
    org.springframework.cache: DEBUG
