spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:prod_database}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  # Redis 설정 (운영환경)
  redis:
    host: ${REDIS_HOST:redis-server}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
    timeout: 2000ms
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

server:
  port: ${SERVER_PORT:8080}

# 커스텀 설정
app:
  icon:
    base-url: /icons

# 이미지 설정 (운영환경)
image:
  upload:
    path: ${IMAGE_UPLOAD_PATH:/app/uploads/products/}
    max-file-size: 10MB
    max-request-size: 10MB
  base-url: ${IMAGE_BASE_URL:https://cdn.shopmall.com/api/images/products/}

# 운영환경용 캐시 설정 (긴 TTL)
cache:
  product:
    detail:
      ttl: 3600 # 1시간
    list:
      ttl: 600 # 10분
    category:
      ttl: 1800 # 30분
    related:
      ttl: 1200 # 20분
  category:
    main:
      ttl: 7200 # 2시간
    children:
      ttl: 1800 # 30분

# 외부 서비스 URL
user-service-detail-url: ${USER_SERVICE_DETAIL_URL:http://user-service/api/users}

# JWT 설정
jwt:
  secret: "verySecretKeyThatIsAtLeast32BytesLong1234"

# 로깅 설정 (운영환경)
logging:
  level:
    com.yourcompany.productcatalog: INFO
    org.kosa.categoryservice: INFO
    org.kosa.productservice: INFO
    org.kosa.imageservice: INFO
    org.springframework.cache: WARN
    redis.clients.jedis: WARN
    root: WARN
