spring:
  application:
    name: user-service

server:
  port: 8103

  datasource:
    url: ${DEV_DB_URL:jdbc:mariadb://localhost:3306/shopmalls?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul}
    username: ${DEV_DB_USERNAME:kosa}
    password: ${DEV_DB_PASSWORD:1004}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  redis:
    host: ${DEV_REDIS_HOST:localhost}
    port: ${DEV_REDIS_PORT:6379}
    password: ${DEV_REDIS_PASSWORD:}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

  kafka:
    bootstrap-servers: ${DEV_KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      enable-idempotence: true
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "org.kosa.userservice.dto"

# MyBatis 설정
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.kosa.userservice.dto.board
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Kafka 토픽 설정
kafka:
  topic:
    user-withdrawal: ${DEV_KAFKA_TOPIC_USER_WITHDRAWAL:user-withdrawal-topic}

# Auth Service 설정
auth-service:
  url: ${DEV_AUTH_SERVICE_URL:http://localhost:8082}

logging:
  level:
    org.kosa.userservice: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.mybatis: DEBUG
